export default function () {
  return {
    logo: require('./assets/images/bg-buildings.png'),
  }
}
export const imageConstant = {
  rightArrow: require('../../src/Assets/chevron.png'),
  closeIcon: require('../../src/Assets/close_btn.png'),
  leftArrow: require('../../src/Assets/back_blue.png'),
  check: require('../Assets/check.png'),
  auth_bg: require('../Assets/auth_bg.png'),
  auth_screen_img: require('../../src/Assets/auth_screen_img.png'),
  backArow: require('../../src/Assets/BackArrow.png'),
  leftArow: require('../../src/Assets/chevron.png'),
  NoOpenTaskImage: require('../../src/Assets/NoOpenTaskImage.png'),
  InProgressStatus: require('../../src/Assets/InProgressStatus.png'),
  NotStartedImage: require('../../src/Assets/NotStartedImage.png'),
  ReturnDeliveredImage: require('../../src/Assets/ReturnDeliveredImage.png'),
  HomeImageUnSelected: require('../../src/Assets/Home.png'),
  HomeImageSelected: require('../../src/Assets/HomeBlue.png'),
  TaskImage: require('../../src/Assets/task.png'),
  TaskImageBlue: require('../../src/Assets/TaskBlue.png'),
  chevronUpWhite: require('../../src/Assets/chevron-up-white.png'),
  chevronUpBlack: require('../../src/Assets/chevron-up-black.png'),
  attach: require('../../src/Assets/attach.png'),
  threeDotsButton: require('../../src/Assets/three-dots-button.png'),
  camera: require('../../src/Assets/camera.png'),
  upload: require('../../src/Assets/upload.png'),
  photoGallary: require('../../src/Assets/photo-gallary.png'),
  blueBack: require('../../src/Assets/blueBack.png'),
  closeCircle: require('../../src/Assets/close-circle.png'),
  plusCircle: require('../../src/Assets/plus-circle.png'),
  pencil: require('../../src/Assets/pencil.png'),
  close: require('../../src/Assets/close.png'),
  toastError: require('../../src/Assets/toastError.png'),
  toastSuccess: require('../../src/Assets/toastSuccess.png'),
  filledCloseGray: require('../../src/Assets/filled-close-gray.png'),
  crossIcon: require('../../src/Assets/closeicon.png'),
  url_linkIcon: require('../../src/Assets/urllink.png'),
  filledCheckCircle: require('../../src/Assets/filled-check-circle.png'),
  ProfileImage: require('../../src/Assets/Profile.png'),
  ContactLogoImage: require('../../src/Assets/ContactLogoImage.png'),
  rightArrowImage: require('../../src/Assets/rightArrow.png'),
  readImage: require('../../src/Assets/read.png'),
  belImage: require('../../src/Assets/bel.png'),
  menuImage: require('../../src/Assets/menu.png'),
  filesImage: require('../../src/Assets/files.png'),
}
