import { Dimensions, StyleSheet } from 'react-native'
const { width, height } = Dimensions.get('window')
import {
  Colors,
  FontFamily,
  FontSize,
  moderateScale,
  horizontalScale,
  verticalScale,
  factorScale,
  FontWeight,
  MetricsSizes,
} from '../../../theme/constants'

const styles = StyleSheet.create({
  missingDocumentView: {
    flexDirection: 'row',
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(12),
    alignItems: 'center',
  },
  missingDocumentTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    marginLeft: horizontalScale(8),
  },
  // CATEGORY HEADER
  categoryList: {
    marginBottom: verticalScale(16),
  },
  categoryHeader: {
    backgroundColor: Colors.textAndBorderColor,
    flexDirection: 'row',
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(8),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryHeaderCompleted: {
    backgroundColor: 'white',
    borderColor: Colors.borderColor,
    borderWidth: 1,
  },
  categoryTitle: {
    textTransform: 'uppercase',
    color: Colors.white,
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.medium,
    lineHeight: verticalScale(16),
    fontSize: moderateScale(12),
    letterSpacing: horizontalScale(1),
  },
  categoryTitleCompleted: {
    color: Colors.textDullColor,
  },
  subTitleCompleted: {
    color: Colors.greenShade1,
  },
  upArrowIcon: {
    height: horizontalScale(24),
    width: verticalScale(24),
  },
  upArrowRotateIcon: {
    height: horizontalScale(24),
    width: verticalScale(24),
    transform: [{ rotate: '90deg' }],
  },
  upArrowRotateIconCompleted: {
    tintColor: Colors.textColor,
  },
  // NOT COMPLETED
  lineItemNotCompletedView: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(14),
    backgroundColor: Colors.white,
    justifyContent: 'space-between',
    borderBottomColor: Colors.backgroundUploadHome,
    borderBottomWidth: verticalScale(0.3),
  },
  lineItemNotCompletedTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(14),
    lineHeight: horizontalScale(21),
    width: '80%',
  },
  // COMPLETED
  lineItemCompletedView: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: horizontalScale(16),
    paddingVertical: verticalScale(6),
    backgroundColor: Colors.backgroundFooterColor,
    borderBottomColor: Colors.backgroundUploadHome,
    borderBottomWidth: verticalScale(0.3),
  },
  lineItemCompletedCenterView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  lineItemCompletedTitleStatusView: {
    width: '75%',
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  lineItemCompletedTitle: {
    marginLeft: horizontalScale(14),
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(14),
    lineHeight: horizontalScale(21),
  },
  lineItemCompletedStatus: {
    marginLeft: horizontalScale(14),
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(12),
    lineHeight: horizontalScale(16),
    textTransform: 'uppercase',
    color: Colors.grayTint1,
  },
  attachIcon: {
    height: horizontalScale(16),
    width: verticalScale(16),
  },
  fileCount: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(16),
    lineHeight: horizontalScale(19),
    color: Colors.testColorBlue,
    marginLeft: horizontalScale(4),
    marginRight: horizontalScale(8),
  },
  attachUpIcon: {
    height: horizontalScale(16),
    width: verticalScale(16),
  },
  attachUpIconRotate: {
    height: horizontalScale(16),
    width: verticalScale(16),
    transform: [{ rotateX: '180deg' }],
  },
  fileCountBox: {
    paddingHorizontal: horizontalScale(8),
    paddingVertical: verticalScale(4),
    borderColor: Colors.borderColor,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  threeDotsIcon: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    height: horizontalScale(18),
    width: verticalScale(18),
    marginLeft: horizontalScale(16),
  },
  attachItemTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(14),
    lineHeight: horizontalScale(18),
    color: Colors.textColor,
    width: '80%',
  },
  attachmentItem: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: verticalScale(14),
    paddingLeft: horizontalScale(51),
    paddingRight: horizontalScale(16),
    backgroundColor: Colors.backgroundFooterColor,
    borderBottomColor: Colors.backgroundUploadHome,
    borderBottomWidth: verticalScale(0.3),
  },
  // UNCATEGORIES ATTACHMENTS
  unCategorizedTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(14),
    lineHeight: horizontalScale(21),
    color: Colors.textAndBorderColor,
    width: '80%',
  },
  // ADD NEW DOCUMENT
  safeAreaModalBody: {
    flex: 1,
    backgroundColor: '#35353580',
  },
  mainView: {},
  topView: {
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(12),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  addNewDocumentTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.medium,
    fontSize: moderateScale(16),
    lineHeight: horizontalScale(19),
    color: Colors.textColor,
  },
  addNewDocumentDescription: {
    marginTop: verticalScale(5),
    marginHorizontal: horizontalScale(56),
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.light,
    fontSize: moderateScale(12),
    lineHeight: horizontalScale(14),
    color: Colors.textColor,
    textAlign: 'center',
  },
  itemsList: {
    marginHorizontal: horizontalScale(49),
    marginVertical: verticalScale(16),
    alignSelf: 'center',
  },
  addNewDocumentItem: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  addNewDocumentImage: {
    width: horizontalScale(32),
    height: verticalScale(32),
    marginBottom: verticalScale(8),
  },
  addNewDocumentItemTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(14),
    lineHeight: horizontalScale(21),
    color: Colors.textColor,
  },
  addNewDocumentListSeprator: {
    width: horizontalScale(30),
  },
  addNewDocumentLineSeprator: {
    height: verticalScale(1),
    width: '100%',
    backgroundColor: Colors.borderColor,
  },
  statusMenuItem: {
    paddingHorizontal: horizontalScale(16),
    paddingTop: verticalScale(13),
    paddingBottom: verticalScale(14),
    borderBottomColor: Colors.backgroundUploadHome,
    borderBottomWidth: verticalScale(0.3),
    width: '100%',
  },
  // PDF CONVERSION
  safeAreaPDFCoversionBody: {
    flex: 1,
    backgroundColor: 'white',
  },
  photosHorizontalList: {
    height: factorScale(height, 0.6),
  },
  photosContainerView: {
    backgroundColor: Colors.backgroundFooterColor,
    height: '100%',
    width: width,
  },
  photoView: {
    flex: 1,
    width: factorScale(width, 0.6),
    height: factorScale(height, 0.6),
    alignSelf: 'center',
    marginTop: verticalScale(43),
    backgroundColor: Colors.white,
  },
  pageIndex: {
    fontFamily: FontFamily.FiraSansRegular,
    fontSize: FontSize.tinyx,
    lineHeight: verticalScale(14),
    fontWeight: FontWeight.normal,
    color: Colors.greenShade,
    marginTop: verticalScale(26),
    marginBottom: verticalScale(8),
    marginRight: verticalScale(8),
    alignSelf: 'flex-end',
  },
  removeImageButton: {
    width: horizontalScale(32),
    height: verticalScale(32),
    position: 'absolute',
    zIndex: 1000,
    marginLeft: factorScale(width, 0.55),
    marginTop: verticalScale(-10),
  },
  bottomItemsView: {
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: verticalScale(16),
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: verticalScale(10),
    marginBottom: horizontalScale(32),
  },
  pagingDot: {
    width: verticalScale(16),
    height: verticalScale(16),
    borderRadius: verticalScale(8),
    marginHorizontal: horizontalScale(4),
  },
  cancelButton: {
    alignSelf: 'center',
    left: horizontalScale(16),
    position: 'absolute',
  },
  pagingDotContainer: {
    position: 'relative',
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
  },
  pagingDotCon: {
    alignSelf: 'center',
    alignItems: 'center',
  },
  bottomGuideContainer: {
    paddingHorizontal: horizontalScale(12),
  },
  bottomGuideText: {
    textAlign: 'center',
    fontFamily: FontFamily.FiraSansMedium,
    fontSize: FontSize.tiny,
    lineHeight: verticalScale(17),
    fontWeight: FontWeight.medium,
  },
  removeButtonImage: {
    width: '100%',
    height: '100%',
  },
  previewImage: {
    width: '100%',
    height: '100%',
  },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  previewFileInput: {
    width: horizontalScale(230),
    height: verticalScale(38),
    marginBottom: verticalScale(16),
    marginTop: verticalScale(16),
    backgroundColor: 'white',
    paddingHorizontal: 0,
    textAlign: 'auto',
  },
  pencilImage: {
    height: verticalScale(16),
    width: horizontalScale(16),
    marginLeft: verticalScale(8),
  },
  saveButtonText: {
    marginLeft: verticalScale(8),
    color: Colors.textAndBorderColor,
    fontSize: FontSize.tiny,
    fontWeight: FontWeight.normal,
  },
  // REPLY WITH AMOUNT
  drlItemDescription: {
    fontFamily: FontFamily.FiraSansRegular,
    fontWeight: FontWeight.normal,
    fontSize: moderateScale(14),
    lineHeight: horizontalScale(21),
    color: Colors.textColor,
    marginLeft: verticalScale(16),
    marginTop: verticalScale(15),
  },
  textField: {
    marginTop: verticalScale(16),
    marginBottom: verticalScale(16),
  },
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  containerView: {
    flex: 1,
  },
  replyContainer: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: horizontalScale(16),
    paddingTop: verticalScale(13),
    paddingBottom: verticalScale(14),
    borderBottomColor: Colors.backgroundUploadHome,
    borderBottomWidth: verticalScale(0.3),
  },
  replyAmountClose: {
    width: horizontalScale(24),
    height: verticalScale(24),
    justifyContent: 'flex-end',
  },
  replyAmountCenterView: {
    justifyContent: 'space-between',
    flex: 1,
  },
  replyAmountCorrectImage: {
    width: horizontalScale(18),
    height: verticalScale(18),
    marginRight: verticalScale(8),
  },
})
export default styles
