import { StyleSheet, Dimensions } from "react-native"
import {
  Colors,
  FontFamily,
  FontSize,
  horizontalScale,
  MetricsSizes,
  moderateScale,
  verticalScale,
} from "../../../theme/constants"

const styles = StyleSheet.create({
  containers: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  scrollView: {
    marginBottom: 20,
  },
  item: {
    backgroundColor: Colors.white,
    height: verticalScale(50),
  },
  itemView: {
    backgroundColor: Colors.white,
    height: moderateScale(44),
    marginStart: moderateScale(5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  horizontalLine2: {
    width: "100%",
    alignSelf: "center",
    backgroundColor: Colors.lineColorGray,
    height: 1,
    marginTop: verticalScale(2),
  },
  horizontalLine: {
    margin: verticalScale(10),
    marginVertical: verticalScale(15),
  },
  headerStyle: {
    flexDirection: "row",
    height: MetricsSizes.regular + 2,
    backgroundColor: Colors.white,
  },
  headerView: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  headerRowStyle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backArrowStyle: {
    width: horizontalScale(18),
    height: verticalScale(18),
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginLeft: horizontalScale(10),
  },
  dependentItem: {
    fontSize: moderateScale(16),
    fontStyle: "normal",
    marginLeft: horizontalScale(16),
    marginVertical: verticalScale(8),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: "30%",
  },
  dependentMainItem: {
    fontSize: moderateScale(16),
    fontStyle: 'normal',
    marginLeft: moderateScale(16),
    marginVertical: moderateScale(8),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: '90%',
    paddingRight: moderateScale(10),
  },
  assetsView: {
    marginTop: verticalScale(10),
    backgroundColor: Colors.white,
  },
  img: {
    width: horizontalScale(10),
    height: verticalScale(15),
    right: horizontalScale(5),
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
  },

  equipmentView: {
    flexDirection: "row",
    marginTop: horizontalScale(10),
  },

  priceView: {
    flexDirection: "row",
    marginTop: horizontalScale(2),
    marginBottom: horizontalScale(10),
  },
  equipmentText: {
    fontSize: moderateScale(16),
    fontStyle: "normal",
    marginLeft: horizontalScale(16),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: "90%",
  },
  purchasesText: {
    fontSize: moderateScale(14),
    fontStyle: "normal",
    marginLeft: horizontalScale(16),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: "50%",
  },
  addTo: {
    fontSize: moderateScale(16),
    fontStyle: "normal",
    marginLeft: horizontalScale(16),
    marginVertical: verticalScale(8),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.testColorBlue,
    width: "100%",
  },
  headerTo: {
    fontSize: moderateScale(14),
    fontStyle: "normal",
    marginLeft: horizontalScale(4),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.testColorBlue,
  },
  assetsText: {
    fontSize: moderateScale(14),
    fontStyle: "normal",
    marginLeft: horizontalScale(4),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: "80%",
  },
  saveText: {
    fontSize: moderateScale(16),
    fontStyle: "normal",
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.testColorBlue,
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  stylesSwipeViewStyle: {
    fontSize: FontSize.tiny,
    height: verticalScale(40),
    backgroundColor: Colors.swipeBackgroundTextColor,
    alignSelf: "center",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    width: horizontalScale(100),
    alignContent: "center",
  },
  rowBack: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    paddingLeft: horizontalScale(10),
  },
  stylesSwipeTextStyle: {
    color: "#ffffff",
  },
  swipeListViewStyle: {
    maxHeight: verticalScale(390),
  },
  mainViewStyle: {
    backgroundColor: Colors.white,
  },
  datePickerContrainer: {
    marginTop: verticalScale(1),
    marginBottom: verticalScale(1),
    width: "100%",
  },
  containerStyle: {
    width: "50%",
  },
  leftSlotViewStyle: {
    width: "40%",
  },
  centerSlotViewStyle: {
    width: horizontalScale(160),
    marginHorizontal: 0,
    paddingHorizontal: 0,
  },
  rightSlotViewStyle: {
    width: horizontalScale(280),
    marginRight: moderateScale(140),
    paddingRight: moderateScale(150),
  },
  textStyleOther: {
    color: Colors.blueShadeColor,
    fontSize: FontSize.tiny,
    fontWeight: "500",
    width: horizontalScale(180),
    marginLeft: -30,
  },
  textStyleOther3: {
    color: Colors.blueShadeColor,
    fontSize: FontSize.tiny,
    fontWeight: "500",
    width: horizontalScale(180),
  },
  textStyleOther1: {
    color: Colors.blueShadeColor,
    fontSize: FontSize.tiny,
    fontWeight: "500",
    width: horizontalScale(180),
    marginLeft: "17%",
  },
  IRSTitle: { fontSize: 15, textAlign: "left", marginRight: 10, margin: 10 },
  AllExpense: { fontSize: 15, textAlign: "right", marginRight: 10 },
  OtherExpense: { fontSize: 15, textAlign: "left", marginLeft: 15 },
  renderItemTitle: { flexDirection: "row" },
  vehicleDecContainer: { flexDirection: "row" },
  vehicleDec: { width: "80%" },
  saveButton: {
    height: 46,
    width: 80,
    marginTop: 22,
    marginLeft: -17,
    justifyContent: "center",
    backgroundColor: Colors.testColorBlue,
  },
  saveButtonText: { color: Colors.white, fontSize: 18, textAlign: "center" },
  saveButton1: {
    color: Colors.blueText,
    marginRight: 16,
    fontSize: 16,
    fontWeight: "400",
  },
  cancelButton: {
    color: Colors.blueText,
    marginLeft: 16,
    fontSize: 16,
    fontWeight: "400",
  },
  flatListItemLeft: {
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "50%",
  },
  renderItemBackground: {
    backgroundColor: Colors.white,
    paddingRight: horizontalScale(10),
  },
  dependentItemDetails: {
    fontSize: moderateScale(12),
    fontStyle: "normal",
    marginLeft: moderateScale(16),
    marginVertical: moderateScale(3),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.gray,
    width: "90%",
    textTransform: "uppercase",
  },
  dependentItemDetailsRight: {
    fontSize: moderateScale(15),
    fontStyle: "normal",
    marginVertical: verticalScale(3),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.gray,
    width: "80%",
    textAlign: "right",
    textTransform: "uppercase",
  },
  flatListItemRight: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    width: '50%',
    right: horizontalScale(30)
  },
})

export default styles
