# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - develop


variables:
  - group: Mobile
  
pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.14.2'
    checkLatest: true
  displayName: 'Install Node.js'
- task: CmdLine@2
  inputs:
    script: 'npm i @react-native-community/cli-platform-android'
- script: |
    # Disable autocommit on version bump 
    yarn config set version-sign-git-tag false
    yarn config set version-git-tag false
    yarn config set version-commit-hooks false
    # Checkout branch where the build is triggered
    git checkout $(Build.SourceBranchName)
    # Extract existing version of package.json
    oldVer=$(jq -r ".version" package.json)
    # Bump version
    yarn version --patch
    # Add bumped version to staging
    git add *
    # Extract new version of package.json
    newVer=$(jq -r ".version" package.json)
    # Set environment variables
    echo "##vso[task.setvariable variable=OLD_VERSION]$oldVer"
    echo "##vso[task.setvariable variable=NEW_VERSION]$newVer"
  displayName: 'Bump version and set variables'

- task: Gradle@2
  displayName: 'Build APK'
  inputs:
      gradleWrapperFile: 'android/gradlew'
      workingDirectory: 'android/'
      options: '-PversionName=$(NEW_VERSION) -PversionCode=$(Build.BuildId)'
      tasks: 'assembleRelease'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.apk'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'WK_TAX_APP_TEST_API_TOKEN'
    appSlug: 'WKTaxApp-Android/ENV_TEST'
    appFile: 'android/app/build/outputs/apk/release/app-release.apk'
    buildVersion: '$(NEW_VERSION)'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'Dev  build'
    destinationType: 'groups'
    distributionGroupId: '581dbcd4-8335-4f6b-8271-309f07127072'
    isSilent: false

