import { questionListType } from '../../utils'
import { t } from 'i18next'

export const deductionandCreditsData: questionListType[] = [
  {
    type: 'segment',
    title: t('dynamicquestions:NAVDEDUCTIONS'),
    APIkey: 'NavDeductions',
    id: 0,
    enable: false,
    value: '',
    isHeaderQuestion: false,
  },
  {
    headerTitle:
      t('dynamicquestions:IN') + ' ${YEAR} ' + t('dynamicquestions:DID_YOU'),
    type: 'segment',
    title: t('dynamicquestions:YNOMEDDENTAL'),
    APIkey: 'ynoMedDental',
    id: 1,
    enable: true,
    value: '',
    isHeaderQuestion: true,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNORETAXES'),
    APIkey: 'ynoRETaxes',
    id: 2,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOPPTAXES'),
    APIkey: 'ynoPPTaxes',
    id: 3,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOMORTGAGEINT'),
    APIkey: 'ynoMortgageInt',
    id: 4,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOCHARITABLECONT'),
    APIkey: 'ynoCharitableCont',
    id: 5,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOCONTRIBUTEPROP'),
    APIkey: 'ynoContributeProp',
    id: 6,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOINVETINENERGYIMPRMTS'),
    APIkey: 'ynoInvetInEnergyImprmts',
    id: 7,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOCASUALTYLOSS'),
    APIkey: 'ynoCasualtyLoss',
    id: 8,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOSPECIALFUELS'),
    APIkey: 'ynoSpecialFuels',
    id: 9,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
]
