import { questionListType } from '../../utils'
import { t } from 'i18next'

export const investment: questionListType[] = [
  {
    type: 'segment',
    title: t('dynamicquestions:NAVINVESTMENTS'),
    APIkey: 'NavInvestments',
    id: 0,
    enable: false,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNORECINTDIV'),
    APIkey: 'ynoRecIntDiv',
    id: 1,
    enable: true,
    value: '',
    isHeaderQuestion: true,
    headerTitle:
      t('dynamicquestions:IN') + ' ${YEAR} ' + t('dynamicquestions:DID_YOU'),
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNODEBTS'),
    APIkey: 'ynoDebts',
    id: 2,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNONEWPARTNERSHIP'),
    APIkey: 'ynoNewPartnership',
    id: 3,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOSELLFARM'),
    APIkey: 'ynoSellFarm',
    id: 4,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOSELLRE'),
    APIkey: 'ynoSellRE',
    id: 5,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOSTOCKOPTIONS'),
    APIkey: 'ynoStockOptions',
    id: 6,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOPUTCALL'),
    APIkey: 'ynoPutCall',
    id: 7,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOSELLSEC'),
    APIkey: 'ynoSellSec',
    id: 8,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOSELLBITCOIN'),
    APIkey: 'ynoSellBitCoin',
    id: 9,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
]
