import { StyleSheet, Dimensions } from 'react-native'

import {
  Colors,
  FontFamily,
  FontSize,
  moderateScale,
  horizontalScale,
  verticalScale,
} from '../../theme/constants'

const styles = StyleSheet.create({
  safeAreaViewStyle: {
    backgroundColor: Colors.white,
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  grayArea: {
    width: '100%',
    height: moderateScale(10),
    backgroundColor: Colors.backgroundFooterColor,
  },
  grayTextArea: {
    width: '100%',
    paddingHorizontal: moderateScale(15),
    paddingTop: verticalScale(10),
    backgroundColor: Colors.backgroundFooterColor,
  },

  leftView: {
    width: '70%',
    marginStart: horizontalScale(15),
  },
  horizontalLine: {
    width: '100%',
    alignSelf: 'center',
    backgroundColor: Colors.lineColorGray,
    height: 1,
  },
  yesButton: {
    width: moderateScale(65),
    height: moderateScale(35),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
  },
  leftText: {
    fontSize: moderateScale(14),
    textAlign: 'left',
    fontWeight: '400',
    width: '100%',
  },
  checkIfText: {
    fontSize: FontSize.small,
    textAlign: 'left',
    fontWeight: '400',
    width: '100%',
    marginTop: verticalScale(30),
    marginStart: horizontalScale(15),
    marginBottom: verticalScale(5),
  },
  grayTitleText: {
    fontSize: moderateScale(12),
    textAlign: 'left',
    width: '100%',
    fontWeight: '500',
    color: Colors.grayTint1,
  },
  grayText: {
    marginTop: moderateScale(10),
    fontSize: moderateScale(14),
    textAlign: 'left',
    width: '100%',
    fontWeight: '300',
  },
  labelStyle: {
    fontWeight: '400',
  },
  rightViewContainer: {
    marginRight: '75%',
    width: '50%',
  },
  textStyle: {
    fontSize: moderateScale(14),
  },
  swipeListViewStyle: {
    maxHeight: Dimensions.get('window').height - moderateScale(390),
  },
  item: {
    backgroundColor: Colors.white,
    height: moderateScale(44),
    paddingEnd: horizontalScale(10),
    marginStart: moderateScale(5),
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  blackItem: {
    backgroundColor: Colors.white,
    height: moderateScale(0),
    width: '100%',
  },
  listitem: {
    fontSize: moderateScale(17),
    fontStyle: 'normal',
    marginLeft: moderateScale(16),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: '90%',
  },
  expItem: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    alignContent: 'flex-end',
    marginRight: moderateScale(30),
  },
  expLeftItem: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    alignContent: 'flex-start',
  },
  expListitem: {
    fontSize: FontSize.tinyx,
    fontStyle: 'normal',
    fontFamily: FontFamily.FiraSansRegular,
    marginLeft: horizontalScale(30),
  },
  expListsubitem: {
    fontSize: FontSize.tiny,
    fontStyle: 'normal',
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    marginLeft: horizontalScale(30),
  },
  switchTxt: {
    fontSize: moderateScale(14),
    fontStyle: 'normal',
    marginLeft: moderateScale(16),
    marginVertical: moderateScale(8),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: '90%',
  },
  switchSubTxt: {
    fontSize: moderateScale(12),
    fontStyle: 'normal',
    marginLeft: moderateScale(16),
    marginVertical: moderateScale(8),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.backgroundUploadHome,
    width: '90%',
    fontWeight: '400',
  },
  headerText: {
    fontSize: FontSize.tiny,
    fontStyle: 'normal',
    fontWeight: '500',
    marginHorizontal: moderateScale(16),
    marginVertical: moderateScale(8),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.testColordarkBlue,
    width: '85%',
  },
  addItem: {
    fontSize: moderateScale(17),
    fontStyle: 'normal',
    marginLeft: moderateScale(16),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.testColorBlue,
    width: '90%',
  },
  dependentItemDetails: {
    color: Colors.testColorBlue,
    width: '55%',
    marginHorizontal: moderateScale(10),
  },
  listTitleStyle: {
    fontSize: moderateScale(16),
    fontStyle: 'normal',
    marginLeft: moderateScale(16),
    marginVertical: moderateScale(8),
    fontFamily: FontFamily.FiraSansRegular,
    color: Colors.black,
    width: '30%',
  },
  horizontalLine2: {
    width: '95%',
    alignSelf: 'center',
    backgroundColor: Colors.lineColorGray,
    height: 1,
    marginTop: moderateScale(2),
    marginStart: moderateScale(25),
  },
  rowBack: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  row: {
    flexDirection: 'row',
    paddingEnd: horizontalScale(10),
    backgroundColor: Colors.white,
    marginTop: verticalScale(-1),
    marginBottom: verticalScale(10),
    justifyContent: 'space-between',

  },
  rowStyle: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginVertical: verticalScale(16),
  },
  stylesSwipeViewStyle: {
    fontSize: FontSize.tiny,
    height: moderateScale(40),
    backgroundColor: Colors.swipeBackgroundTextColor,
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: moderateScale(100),
    alignContent: 'center',
  },
  saveBtnViewStyle: {
    fontSize: FontSize.tiny,
    height: moderateScale(40),
    backgroundColor: Colors.textAndBorderColor,
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: moderateScale(100),
  },
  saveContainer: {
    alignSelf: 'stretch',
    display: 'flex',
    flexGrow: 1,
    marginHorizontal: horizontalScale(16),
  },
  dropDownContainer: {
    marginTop: verticalScale(16),
    marginBottom: verticalScale(16),
  },
  scrolViewContainer: {
    backgroundColor: Colors.white,
  },
  deleteBtnViewStyle: {
    height: moderateScale(44),
    backgroundColor: Colors.swipeBackgroundTextColor,
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: '90%',
    alignContent: 'center',
    marginTop: moderateScale(28),
  },
  stylesSwipeTextStyle: {
    color: Colors.white,
  },
  deleteTextStyle: {
    color: Colors.white,
    fontWeight: '400',
    fontSize: FontSize.smallx,
  },
  img: {
    width: moderateScale(20),
    height: moderateScale(20),
    right: moderateScale(5),
    resizeMode:'contain'
  },
  buttonContactStyle: {
    flex: 1,
    alignSelf: 'center',
    height: moderateScale(44),
    borderRadius: 0,
    backgroundColor: Colors.testColorBlue,
  },
  buttonDoneContactStyle: {
    fontSize: moderateScale(14),
    justifyContent: 'center',
    textAlign: 'center',
    color: Colors.white,
    fontFamily: FontFamily.FiraSansRegular,
  },
  buttonFinishContactStyle: {
    flex: 1,
    alignSelf: 'center',
    backgroundColor: Colors.white,
    borderColor: Colors.borderColor,
    borderWidth: 0,
    borderRadius: 0,
    height: moderateScale(44),
  },
  buttonConatinerStyle: {
    height: moderateScale(44),
    flexDirection: 'row',
    alignContent: 'center',
    backgroundColor: Colors.white,
  },
  stylesContainerText: {
    justifyContent: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    fontWeight: '300',
    color: Colors.black,
    fontSize: moderateScale(14),
    marginTop: moderateScale(5),
  },
  tabIndicatorStyle: { backgroundColor: Colors.blueShade1 },
  tarBarStyle: { backgroundColor: Colors.white },
  amountTxtStyle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontSize: FontSize.tinyx,
    marginEnd: horizontalScale(16),
    fontWeight: '500',
    textAlign: 'right',
    padding: horizontalScale(16),
    color: Colors.testColordarkBlue,
  },
  // HEADER
  headerContainer: {
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    paddingHorizontal: horizontalScale(16),
  },
  headerTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontSize: FontSize.smallx,
    textAlign: 'center',
  },
  headerSubTitle: {
    fontFamily: FontFamily.FiraSansRegular,
    fontSize: FontSize.small,
    textAlign: 'center',
  },
  headerSubTitleForBRF: {
    fontFamily: FontFamily.FiraSansRegular,
    fontSize: FontSize.tinyx,
    textAlign: 'center',
    width: '60%',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  headerButtonText: {
    color: Colors.textAndBorderColor,
    fontSize: FontSize.small,
  },
  vehicleDecContainer: { flexDirection: 'row' },
  vehicleDec: { width: '80%' },
  containerStyle: {
    width: '50%',
    marginTop: verticalScale(20),
  },
  saveButton: {
    height: verticalScale(45),
    width: horizontalScale(80),
    marginTop: verticalScale(22),
    marginLeft: horizontalScale(-17),
    justifyContent: 'center',
    backgroundColor: Colors.testColorBlue,
  },
  blankStyle: {
    backgroundColor: Colors.white,
  },
  saveButtonText: {
    color: Colors.white,
    fontSize: FontSize.smallx,
    textAlign: 'center',
  },
  datePickerContrainer: {
    marginTop: verticalScale(20),
    marginBottom: verticalScale(1),
    width: '100%',
  },
  seprationYesNo: { width: 0.1 },
  checkboxStyle: {
    alignSelf: 'center',
    width: moderateScale(18),
    height: moderateScale(18),
    borderRadius: 0,
  },
  checkboxTextStyle: {
    fontSize: moderateScale(14),
    width: moderateScale(240),
  },
  checkBoxViewStyle: {
    paddingBottom: horizontalScale(8),
    paddingTop: horizontalScale(8),
    flexDirection: 'row',
    alignContent: 'space-between',
    justifyContent: 'space-between',
    marginHorizontal: horizontalScale(15),
  },
})

export default styles
