import { questionListType } from '../../utils'
import { t } from 'i18next'

export const healthcare: questionListType[] = [
  {
    type: 'segment',
    title: t('dynamicquestions:NAVHEALTHCARE'),
    APIkey: 'NavHealthcare',
    id: 0,
    enable: false,
    value: '',
    isHeaderQuestion: false,
  },
  {
    headerTitle:
      t('dynamicquestions:IN') + ' ${YEAR} ' + t('dynamicquestions:DID_YOU'),
    type: 'segment',
    title: t('dynamicquestions:YNOHEALTHCARECOVERAGE'),
    APIkey: 'ynoHealthCareCoverage',
    id: 1,
    enable: true,
    value: '',
    isHeaderQuestion: true,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOMARKETPLACECOVERAGE'),
    APIkey: 'ynoMarketPlaceCoverage',
    id: 2,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNORECPREMCREDIT'),
    APIkey: 'ynoRecPremCredit',
    id: 3,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOREC1095A'),
    APIkey: 'ynoRec1095A',
    id: 4,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOINSOTHERPLAN'),
    APIkey: 'ynoInsOtherPlan',
    id: 5,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOEMPLOYERHEALTHCARE'),
    APIkey: 'ynoEmployerHealthCare',
    id: 6,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOLOSEJOBOWNINS'),
    APIkey: 'ynoLoseJobOwnIns',
    id: 7,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOTRANSHSA'),
    APIkey: 'ynoTransHSA',
    id: 8,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOTRANSMSA'),
    APIkey: 'ynoTransMSA',
    id: 9,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOLTCINS'),
    APIkey: 'ynoLTCIns',
    id: 10,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
]
