export const states: { key: string; value: string }[] = [
  { key: '', value: '' },
  { key: 'AL', value: 'Alabama' },
  { key: 'AK', value: 'Alaska' },
  { key: 'AZ', value: 'Arizona' },
  { key: 'AR', value: 'Arkansas' },
  { key: 'AA', value: 'AA - Overseas military' },
  { key: 'AE', value: 'AE - Overseas military' },
  { key: 'AP', value: 'AP - Overseas military' },
  { key: 'AS', value: 'American Samoa' },
  { key: 'CA', value: 'California' },
  { key: 'CO', value: 'Colorado' },
  { key: 'CT', value: 'Connecticut' },
  { key: 'DE', value: 'Delaware' },
  { key: 'DC', value: 'District of Columbia' },
  { key: 'FM', value: 'Fed States of Micronesia' },
  { key: 'FL', value: 'Florida' },
  { key: 'GA', value: 'Georgia' },
  { key: 'GU', value: 'Guam' },
  { key: 'HI', value: 'Hawaii' },
  { key: 'ID', value: 'Idaho' },
  { key: 'IL', value: 'Illinois' },
  { key: 'IN', value: 'Indiana' },
  { key: 'IA', value: 'Iowa' },
  { key: 'KS', value: 'Kansas' },
  { key: 'KY', value: 'Kentucky' },
  { key: 'LA', value: 'Louisiana' },
  { key: 'ME', value: 'Maine' },
  { key: 'MH', value: 'Marshall Islands' },
  { key: 'MD', value: 'Maryland' },
  { key: 'MA', value: 'Massachusetts' },
  { key: 'MI', value: 'Michigan' },
  { key: 'MN', value: 'Minnesota' },
  { key: 'MS', value: 'Mississippi' },
  { key: 'MO', value: 'Missouri' },
  { key: 'MP', value: 'Commonwealth of Northern Mariana lslands' },
  { key: 'MT', value: 'Montana' },
  { key: 'NE', value: 'Nebraska' },
  { key: 'NV', value: 'Nevada' },
  { key: 'NH', value: 'New Hampshire' },
  { key: 'NJ', value: 'New Jersey' },
  { key: 'NM', value: 'New Mexico' },
  { key: 'NY', value: 'New York' },
  { key: 'NC', value: 'North Carolina' },
  { key: 'ND', value: 'North Dakota' },
  { key: 'OH', value: 'Ohio' },
  { key: 'OK', value: 'Oklahoma' },
  { key: 'OR', value: 'Oregon' },
  { key: 'PW', value: 'Palau' },
  { key: 'PA', value: 'Pennsylvania' },
  { key: 'PR', value: 'Puerto Rico' },
  { key: 'RI', value: 'Rhode Island' },
  { key: 'SC', value: 'South Carolina' },
  { key: 'SD', value: 'South Dakota' },
  { key: 'TN', value: 'Tennessee' },
  { key: 'TX', value: 'Texas' },
  { key: 'UT', value: 'Utah' },
  { key: 'VT', value: 'Vermont' },
  { key: 'VA', value: 'Virginia' },
  { key: 'VI', value: 'Virgin Islands' },
  { key: 'WA', value: 'Washington' },
  { key: 'WV', value: 'West Virginia' },
  { key: 'WI', value: 'Wisconsin' },
  { key: 'WY', value: 'Wyoming' },
]
// For Marital status
export const MaritalStatuses: { key: string; value: string }[] = [
  { key: '', value: '' },
  { key: 'U', value: 'Unmarried' },
  { key: 'L', value: 'Legally married' },
  { key: 'D', value: 'Domestic partnership' },
  { key: 'C', value: 'Civil union' },
  { key: 'O', value: 'Other state defined relationship' },
]
// For account types
export const accTypes: { key: string; value: string }[] = [
  { key: '', value: '' },
  { key: '1', value: 'Checking' },
  { key: '2', value: 'Traditional Savings' },
  { key: '3', value: 'IRA Savings' },
  { key: '4', value: 'HSA Savings' },
  { key: '5', value: 'Archer MSA Savings' },
  { key: '6', value: 'Coverdell Ed. Savings' },
]

// For businessaccount types
export const businessAccountTypes: { key: string; value: string }[] = [
  { key: '', value: '' },
  { key: '1', value: 'Checking' },
  { key: '2', value: 'Savings' },
]
