export enum GridCode {
  OtherBusinessExpenses = '100',
  BusinessAssets = '101',
  BusinessVehicles = '102',
  OtherBusinessVehicles = '103',
  BusinessOffice = '104',
  OtherBusinessOffices = '105',
  OtherBusinessIncome = '106',
  OtherRentalExpenses = '107',
  BusinessRentalVehicles = '102',
  OtherBusinessRentalVehicles = '103',
  RentalOffice = '104',
  OtherRentalOffices = '105',
  BusinessRentalAssets = '108',
  BusinessFarmCashIncome = '109',
  BusinessFarmAccrualIncome = '110',
  BusinessFarmOtherIncome = '111',
  BusinessFarmOtherExpenses = '112',
  BusinessFarmAssets = '113',
  BusinessFarmVehicleOtherExpenses = '114',
  BusinessFarmHomeOffice = '104',
  BusinessFarmHomeOfficeOtherExpenses = '115',
}
