import { t } from 'i18next'

export const aList = [
  {
    type: 'RadionButton',
    title: t('questionnaire:HAVE_ANY_CHANGES_IN_SAHREHOLDER'),
    APIkey: 'first',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25012',
    drl: '0',
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 2,
    headerTitle: t('questionnaire:GENERAL_OWNER'),
  },
  {
    type: 'RadionButton',
    title: t('questionnaire:HAVE_ANY_ACCOUNT_SYSTEM'),
    APIkey: 'second',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25013',
    drl: '0',
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 6,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:HAVE_ANY_AMENDMENTS'),
    APIkey: 'third',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25014',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 8,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:PAYOYT_ANY_DIVIDENDS_OR_DISTRIBUTION'),
    APIkey: 'four',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25015',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 13,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:PAY_SHAREHOLDER_MEDICAL'),
    APIkey: 'five',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25016',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 18,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:ENGAGE_IN_ACTIVITIES_START_OR_DISPOSE'),
    APIkey: 'six',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25017',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 22,
    category: '',
    headerTitle: t('questionnaire:INVESTMENTS'),
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:HOLD_ANY_FOREIGN'),
    APIkey: 'seven',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25018',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 23,
    category: '',
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:HOLD_ANY_INVESTMENS'),
    APIkey: 'eight',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25019',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 24,
  },
  {
    type: 'RadionButton',
    title: t('questionnaire:HOLD_INVESTMENTS_IN_OTHER'),
    APIkey: 'nine',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25020',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 25,
  },
  {
    type: 'RadionButton',
    title: t('questionnaire:ACQUIRE_USE_DIPOSE'),
    APIkey: 'ten',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25021',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 26,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:TAKE_OUT_ANY_NEW'),
    APIkey: 'eleven',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25022',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 28,
    headerTitle: t('questionnaire:DEBT'),
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:HAVE_ANY_OUTSTADING'),
    APIkey: 'twelve',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25023',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 32,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:OPERATE_IN_MULTIPLE'),
    APIkey: 'nineteen',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25024',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 33,
    headerTitle: t('questionnaire:SALES_OPERATION'),
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:FILE_SALES_AND_USE'),
    APIkey: 'thirteen',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25025',
    drlQuestionId: 34,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:RECEIVE_ANY'),
    APIkey: 'fourteen',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25026',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 35,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:MAINTAIN_INVENTORY'),
    APIkey: 'fifteen',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25027',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 36,
  },
  {
    type: 'RadionButton',
    title: t('questionnaire:PREPRARE_OR_WILL'),
    APIkey: 'sixteen',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25028',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 37,
    headerTitle: t('questionnaire:PAYROLL_CONTRACTOR'),
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:PREPRARE_OR_WILL_W_2'),
    APIkey: 'seventeen',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25029',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 38,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:HAVE_ANY_EMPLOYEE'),
    APIkey: 'eighteen',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25030',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 39,
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:HAVE_ANY_MEAL'),
    APIkey: 'twenty',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25031',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 40,
    headerTitle: t('businessRental:Expenses'),
  },

  {
    type: 'RadionButton',
    title: t('questionnaire:MAKE_ANY_CHARITABLE'),
    APIkey: 'twentyOne',
    placeholder: '',
    answer: '',

    validation: [],
    enable: false,
    styles: [],
    id: '25032',
    drl: 0,
    noteBoxTitle: '',
    notesText: '',
    drlQuestionId: 41,
  },
]
