import { questionListType } from '../../utils'
import { t } from 'i18next'

export const foreign: questionListType[] = [
  {
    type: 'segment',
    title: t('dynamicquestions:NAVFOREIGNMATTERS'),
    APIkey: 'NavForeignMatters',
    id: 0,
    enable: false,
    value: '',
    isHeaderQuestion: false,
  },
  {
    headerTitle:
      t('dynamicquestions:IN') + ' ${YEAR} ' + t('dynamicquestions:DID_YOU'),
    type: 'segment',
    title: t('dynamicquestions:YNOFOREIGNWORK'),
    APIkey: 'ynoForeignWork',
    id: 1,
    enable: true,
    value: '',
    isHeaderQuestion: true,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOFOREIGNASSIGNMENT'),
    APIkey: 'ynoForeignAssignment',
    id: 2,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOFAMILYALLOWANCES'),
    APIkey: 'ynoFamilyAllowances',
    id: 3,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOGRANTORFOREIGNTRUST'),
    APIkey: 'ynoGrantorForeignTrust',
    id: 4,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOBENEFICIARYRETIREPLAN'),
    APIkey: 'ynoBeneficiaryRetirePlan',
    id: 5,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOFOREIGNINVESTCOMPANY'),
    APIkey: 'ynoForeignInvestCompany',
    id: 6,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOTRANSFERMONEY'),
    APIkey: 'ynoTransferMoney',
    id: 7,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOINVESTFOREIGNCORP'),
    APIkey: 'ynoInvestForeignCorp',
    id: 8,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
  {
    type: 'segment',
    title: t('dynamicquestions:YNOOWNSHARESMUTUALFUND'),
    APIkey: 'ynoOwnSharesMutualFund',
    id: 9,
    enable: true,
    value: '',
    isHeaderQuestion: false,
  },
]
